apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - dvc-sync-job.yaml
  - service.yaml
  - ingress.yaml
