apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pardon-dvc-data
  namespace: pardon
  labels:
    app.kubernetes.io/name: pardon
    app.kubernetes.io/component: dvc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
