apiVersion: v1
kind: ConfigMap
metadata:
  name: pardon-config
  namespace: pardon
data:
  MLFLOW_TRACKING_URI: "file:/app/mlruns"
  MLFLOW_EXPERIMENT_NAME: "anomaly_detection"
  MLFLOW_INFERENCE_EXPERIMENT_NAME: "anomaly_detection_inference"
  MONITORING_EXPORTER_PORT: "8010"
