apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: pardon-app
    newName: ghcr.io/huh-itmo-y27/pardon
    newTag: latest
