apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: pardon-api
    newName: pardon-api
    newTag: latest
  - name: pardon-ui
    newName: pardon-ui
    newTag: latest
