apiVersion: apps/v1
kind: Deployment
metadata:
  name: pardon-api
  namespace: pardon
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pardon-ui
  namespace: pardon
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
