apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: image-pull-secrets.yaml
images:
  - name: pardon-api
    newName: ghcr.io/huh-itmo-y27/pardon/api
    newTag: 094c3e2d5f70
  - name: pardon-ui
    newName: ghcr.io/huh-itmo-y27/pardon/ui
    newTag: 094c3e2d5f70
